openapi: 3.0.3
info:
  title: Work Camp Doc's
  description: |-
    This is a sample APIs doc for the work camp app
servers:
  - url: http://localhost:8000
tags:
  - name: Camp
    description: All endpoints about the Camp
paths:
  /camp-availability:
    post:
      tags:
        - Camp
      summary: check camp availability.
      description: call this api to chack camp availability.
      requestBody:
        description: call this api to chack camp availability.
        content:
          application/json:
            schema:
              type: object
              properties:
                campName:
                  type: string
                  example: sofit
        required: true
      responses:
        '201': # status code
          description: return with created camp object
        '400': # status code
          description: Invalid body data
