# Specify the base image
FROM node:14-alpine

# Create and set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --only=production

# Copy the rest of the application code
COPY . .

# Expose the port that the application will listen on
EXPOSE 3001

# Start the application
CMD ["npm", "run", "dev"]